language: node_js
node_js:
    - "12"
script:
    - yarn test
    - yarn build
deploy:
    provider: heroku
  api_key: QrNw33xK9r56fkZOPW7cW04rTC56565wfrd2FBiQtuBjMFUy/DK66sqajMAqSeKgHzd4WaszA+CfbL6Obo2Y2qut1C4r7MJFCR+oyuq5MJUe6rI0MVtPfkpGX/NPCrNfdxBJCeQRAX6PYlLOxCRg5iSi+XuwqLJNIy9VQpcF05KRKW2l8IMIpqdHkXdKHM9KOzKSe3egfdMazwgeZ43JLiB8MU37FGWO0fdiNgHdKEGZUPzcLHd7e4SjBsurTriU9b0YPxZDXt6pQIonxdMiJHO8jgpiVi+nfL3ZxvNpArU/HnrBJhUcpz2qCYJsMr07ER7IXqZcHBzBOLLch9W7ATZy860OneYbLwrd+ZYQH7wZynL7pb7c3Yd9AhZQK9pItvlBZ7bY9ckmt/st/n9pqnHhOWHhzBK187MWXiAyarb6F/LRFhsqHVo9S44LxaK0H9I1QuGUK5wuaYGPsgWV0TPxmPuN2mJbWpIqQTwiwfJANu26EX4oWPKka1l8BA9Qi+72iHKgXl0s+AtyhNL8kE5v8VfKcY4CcU9CU2Rr4YuAs5TawVYDhMibV++ZvUd5tawJPgtRGpjw4NtFvZ0Bqvh8OQmv5lThAyUqZzFvVvKdGU6wen+9lIWtntE5pqQQBdSol0hMGwlYqKYUI/bA1jLSsnnuSahoWGn7k5Km9zg=
