export default {
    primaryTextColor: "#000000",
    secondaryTextColor: "#ffffff",
    voteTextColor: "#aa4400",
    linkTextColor: "#a7a39a",
    orangeTextColor: "#fd652e",
    darkTextColor: "#6f6e6e",
    primaryRowColor: "#f5f6ef",
    secondaryRowColor: "#e6e6df",
    mainRowColor: "#ff6702",
    arrowColor: "#999999",
    transparentColor: "transparent",
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    fontSizeMedium: "0.85rem",
    fontSizeSmall: "0.65rem",
    fontSizeMediumSmall: "0.75rem",
    fontSizeBig: "1rem",
};
