export default {
    primaryTextColor: "#000000",
    secondaryTextColor: "#ffffff",
    voteTextColor: "#aa4400",
    linkTextColor: "#a7a39a",
    orangeTextColor: "#fd652e",
    primaryRowColor: "#f5f6ef",
    secondaryRowColor: "#e6e7e0",
    mainRowColor: "#ff6702",
    transparentColor: "transparent",
    fontWeightRegular: 400,
    fontSizeMedium: "0.75rem",
    fontSizeSmall: "0.5rem",
    fontSizeBig: "1rem",
};
